version: '3.9'

services:
  postgresql:
    image: postgres:16.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - database_data:/var/lib/postgresql/data

  userapi:
    build:
        context: .
        dockerfile: ./user-api/Dockerfile
    ports:
      - 5000:5000
    links:
      - postgresql
    environment:
      - PGHOST=postgresql
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
    depends_on:
      - postgresql

  creatureapi:
    build:
      context: .
      dockerfile: ./creature-api/Dockerfile
    ports:
      - 5001:5000
    links:
      - postgresql
    environment:
      - PGHOST=postgresql
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
    depends_on:
      - postgresql
      - userapi

  matchapi:
    build:
      context: .
      dockerfile: ./match-api/Dockerfile
    ports:
      - 5002:5000
    links:
      - postgresql
    environment:
      - PGHOST=postgresql
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
    depends_on:
      - postgresql
      - userapi
      - creatureapi

  proxy:
    image: nginx
    volumes:
      - ./proxy:/etc/nginx:ro
    ports:
      - "80:80"
    depends_on:
      - userapi
      - creatureapi
      - matchapi


volumes:
  database_data:
    driver: local