/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **matches**
   * - Table in database
   */
  export namespace matches {
    export type Table = 'matches';
    export interface Selectable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id: number;
      /**
      * **matches.host**
      * - `varchar` in database
      * - Nullable, no default
      */
      host: string | null;
      /**
      * **matches.challenger**
      * - `varchar` in database
      * - Nullable, no default
      */
      challenger: string | null;
      /**
      * **matches.status**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      status: number | null;
      /**
      * **matches.winner**
      * - `varchar` in database
      * - Nullable, no default
      */
      winner: string | null;
      /**
      * **matches.creation_date**
      * - `timestamp` in database
      * - Nullable, default: `now()`
      */
      creation_date: Date | null;
      /**
      * **matches.beginning_date**
      * - `timestamp` in database
      * - Nullable, no default
      */
      beginning_date: Date | null;
      /**
      * **matches.ending_date**
      * - `timestamp` in database
      * - Nullable, no default
      */
      ending_date: Date | null;
    }
    export interface JSONSelectable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id: number;
      /**
      * **matches.host**
      * - `varchar` in database
      * - Nullable, no default
      */
      host: string | null;
      /**
      * **matches.challenger**
      * - `varchar` in database
      * - Nullable, no default
      */
      challenger: string | null;
      /**
      * **matches.status**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      status: number | null;
      /**
      * **matches.winner**
      * - `varchar` in database
      * - Nullable, no default
      */
      winner: string | null;
      /**
      * **matches.creation_date**
      * - `timestamp` in database
      * - Nullable, default: `now()`
      */
      creation_date: db.TimestampString | null;
      /**
      * **matches.beginning_date**
      * - `timestamp` in database
      * - Nullable, no default
      */
      beginning_date: db.TimestampString | null;
      /**
      * **matches.ending_date**
      * - `timestamp` in database
      * - Nullable, no default
      */
      ending_date: db.TimestampString | null;
    }
    export interface Whereable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.host**
      * - `varchar` in database
      * - Nullable, no default
      */
      host?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.challenger**
      * - `varchar` in database
      * - Nullable, no default
      */
      challenger?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.status**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      status?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.winner**
      * - `varchar` in database
      * - Nullable, no default
      */
      winner?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.creation_date**
      * - `timestamp` in database
      * - Nullable, default: `now()`
      */
      creation_date?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.beginning_date**
      * - `timestamp` in database
      * - Nullable, no default
      */
      beginning_date?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.ending_date**
      * - `timestamp` in database
      * - Nullable, no default
      */
      ending_date?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **matches.host**
      * - `varchar` in database
      * - Nullable, no default
      */
      host?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.challenger**
      * - `varchar` in database
      * - Nullable, no default
      */
      challenger?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.status**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      status?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.winner**
      * - `varchar` in database
      * - Nullable, no default
      */
      winner?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.creation_date**
      * - `timestamp` in database
      * - Nullable, default: `now()`
      */
      creation_date?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.beginning_date**
      * - `timestamp` in database
      * - Nullable, no default
      */
      beginning_date?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.ending_date**
      * - `timestamp` in database
      * - Nullable, no default
      */
      ending_date?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.host**
      * - `varchar` in database
      * - Nullable, no default
      */
      host?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.challenger**
      * - `varchar` in database
      * - Nullable, no default
      */
      challenger?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.status**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      status?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.winner**
      * - `varchar` in database
      * - Nullable, no default
      */
      winner?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.creation_date**
      * - `timestamp` in database
      * - Nullable, default: `now()`
      */
      creation_date?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.beginning_date**
      * - `timestamp` in database
      * - Nullable, no default
      */
      beginning_date?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.ending_date**
      * - `timestamp` in database
      * - Nullable, no default
      */
      ending_date?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'matches_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **rounds**
   * - Table in database
   */
  export namespace rounds {
    export type Table = 'rounds';
    export interface Selectable {
      /**
      * **rounds.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('rounds_id_seq'::regclass)`
      */
      id: number;
      /**
      * **rounds.match_id**
      * - `int4` in database
      * - Nullable, no default
      */
      match_id: number | null;
      /**
      * **rounds.host_creature**
      * - `int4` in database
      * - Nullable, no default
      */
      host_creature: number | null;
      /**
      * **rounds.challenger_creature**
      * - `int4` in database
      * - Nullable, no default
      */
      challenger_creature: number | null;
      /**
      * **rounds.status**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      status: number | null;
      /**
      * **rounds.winner**
      * - `varchar` in database
      * - Nullable, no default
      */
      winner: string | null;
    }
    export interface JSONSelectable {
      /**
      * **rounds.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('rounds_id_seq'::regclass)`
      */
      id: number;
      /**
      * **rounds.match_id**
      * - `int4` in database
      * - Nullable, no default
      */
      match_id: number | null;
      /**
      * **rounds.host_creature**
      * - `int4` in database
      * - Nullable, no default
      */
      host_creature: number | null;
      /**
      * **rounds.challenger_creature**
      * - `int4` in database
      * - Nullable, no default
      */
      challenger_creature: number | null;
      /**
      * **rounds.status**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      status: number | null;
      /**
      * **rounds.winner**
      * - `varchar` in database
      * - Nullable, no default
      */
      winner: string | null;
    }
    export interface Whereable {
      /**
      * **rounds.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('rounds_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rounds.match_id**
      * - `int4` in database
      * - Nullable, no default
      */
      match_id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rounds.host_creature**
      * - `int4` in database
      * - Nullable, no default
      */
      host_creature?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rounds.challenger_creature**
      * - `int4` in database
      * - Nullable, no default
      */
      challenger_creature?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rounds.status**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      status?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rounds.winner**
      * - `varchar` in database
      * - Nullable, no default
      */
      winner?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **rounds.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('rounds_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **rounds.match_id**
      * - `int4` in database
      * - Nullable, no default
      */
      match_id?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rounds.host_creature**
      * - `int4` in database
      * - Nullable, no default
      */
      host_creature?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rounds.challenger_creature**
      * - `int4` in database
      * - Nullable, no default
      */
      challenger_creature?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rounds.status**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      status?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rounds.winner**
      * - `varchar` in database
      * - Nullable, no default
      */
      winner?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **rounds.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('rounds_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **rounds.match_id**
      * - `int4` in database
      * - Nullable, no default
      */
      match_id?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rounds.host_creature**
      * - `int4` in database
      * - Nullable, no default
      */
      host_creature?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rounds.challenger_creature**
      * - `int4` in database
      * - Nullable, no default
      */
      challenger_creature?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rounds.status**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      status?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rounds.winner**
      * - `varchar` in database
      * - Nullable, no default
      */
      winner?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'rounds_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = matches.Table | rounds.Table;
    export type Selectable = matches.Selectable | rounds.Selectable;
    export type JSONSelectable = matches.JSONSelectable | rounds.JSONSelectable;
    export type Whereable = matches.Whereable | rounds.Whereable;
    export type Insertable = matches.Insertable | rounds.Insertable;
    export type Updatable = matches.Updatable | rounds.Updatable;
    export type UniqueIndex = matches.UniqueIndex | rounds.UniqueIndex;
    export type Column = matches.Column | rounds.Column;
  
    export type AllBaseTables = [matches.Table, rounds.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [matches.Table, rounds.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "matches": matches.Selectable;
    "rounds": rounds.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "matches": matches.JSONSelectable;
    "rounds": rounds.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "matches": matches.Whereable;
    "rounds": rounds.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "matches": matches.Insertable;
    "rounds": rounds.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "matches": matches.Updatable;
    "rounds": rounds.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "matches": matches.UniqueIndex;
    "rounds": rounds.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "matches": matches.Column;
    "rounds": rounds.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "matches": matches.SQL;
    "rounds": rounds.SQL;
  }[T];

}
